# NumPy Basics
This notebook provides an introduction to basic operations in NumPy.

In [1]:
# Importing NumPy
import numpy as np

## 1. Creating Arrays

In [2]:
# Creating 1D, 2D, and 3D arrays
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:")
print(array_1d)
print("\n2D Array:")
print(array_2d)
print("\n3D Array:")
print(array_3d)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 2. Array Attributes

In [3]:
# Exploring shape, size, and dimensions
print("Shape of 2D Array:", array_2d.shape)
print("Number of elements in 1D Array:", array_1d.size)
print("Number of dimensions in 3D Array:", array_3d.ndim)

Shape of 2D Array: (2, 3)
Number of elements in 1D Array: 5
Number of dimensions in 3D Array: 3


## 3. Array Initialization

In [4]:
# Creating arrays using built-in functions
zeros = np.zeros((2, 3))  # 2x3 array of zeros
ones = np.ones((3, 2))    # 3x2 array of ones
random_array = np.random.rand(3, 3)  # 3x3 random values
range_array = np.arange(0, 10, 2)    # Even numbers from 0 to 8

print("Zeros Array:")
print(zeros)
print("\nOnes Array:")
print(ones)
print("\nRandom Array:")
print(random_array)
print("\nRange Array:")
print(range_array)

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

Random Array:
[[0.07302236 0.76302157 0.12529131]
 [0.81221222 0.16028004 0.17783591]
 [0.15929317 0.47780996 0.58906158]]

Range Array:
[0 2 4 6 8]


## 5. Array Operations

In [5]:
# Performing basic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


## 6. Reshaping Arrays

In [6]:
# Calculating mean, sum, and standard deviation
print("Mean:", array_2d.mean())
print("Sum:", array_2d.sum())
print("Standard Deviation:", array_2d.std())

Mean: 3.5
Sum: 21
Standard Deviation: 1.707825127659933


## 8. Broadcasting

In [7]:
# Adding a scalar to an array
scalar_added = array_1d + 10
print("Original 1D Array:", array_1d)
print("After Adding 10:", scalar_added)

Original 1D Array: [1 2 3 4 5]
After Adding 10: [11 12 13 14 15]
